"""
GENERATED BY METIS - DO NOT EDIT DIRECTLY
Generated at: 2025-12-29T08:04:29.093656
Project: syrinx

Source: metis/shared/models/
To modify, edit the JSON Schema files and run: python metis/shared/sync.py
"""

from datetime import date
from typing import Literal, Any
from pydantic import BaseModel

AllergyReactionType = Literal["allergy", "intolerance"]

class CodeableConcept(BaseModel):
  """A coded concept with system, code, and display text"""
  system: str
  code: str
  display: str

class DoseChange(BaseModel):
  """Record of a medication dose change"""
  date: date
  previous_dose: str
  new_dose: str

MedicationStatus = Literal["active", "completed", "stopped", "on-hold"]

AllergyCategory = Literal["food", "medication", "environment", "biologic"]

ConditionStatus = Literal["active", "recurrence", "relapse", "inactive", "remission", "resolved"]

class EncounterSummary(BaseModel):
  """Brief encounter summary for context"""
  id: str | None = None
  date: date
  type: str
  chief_complaint: str
  diagnoses: list[str] | None = None
  provider: str | None = None
  notes: str | None = None

Severity = Literal["mild", "moderate", "severe"]

class InjectedError(BaseModel):
  """An error injected into an encounter for training"""
  category: Literal["clinical", "communication", "documentation"]
  type: str
  description: str | None = None

class ScriptLine(BaseModel):
  """A line of dialogue in an encounter script"""
  speaker: str
  text: str
  direction: str | None = None
  timestamp: float | None = None

VerificationStatus = Literal["confirmed", "provisional", "differential", "refuted", "unconfirmed"]

class AllergyReaction(BaseModel):
  """A reaction manifestation for an allergy"""
  manifestation: str
  severity: Literal["mild", "moderate", "severe", "life-threatening"] | None = None

class Medication(BaseModel):
  """A medication on the patient's list (matches Oread patient.py:609)"""
  id: str
  code: CodeableConcept
  display_name: str
  status: MedicationStatus | None = None
  dose_quantity: str
  dose_unit: str
  frequency: str
  route: str | None = 'oral'
  instructions: str | None = None
  prn: bool | None = False
  prn_reason: str | None = None
  start_date: date
  end_date: date | None = None
  prescribed_at_encounter: str | None = None
  indication: str | None = None
  indication_condition_id: str | None = None
  prescriber: str | None = None
  pharmacy: str | None = None
  refills_remaining: int | None = None
  dose_changes: list[DoseChange] | None = None
  discontinuation_reason: str | None = None

class Condition(BaseModel):
  """A medical condition/diagnosis (matches Oread patient.py:569)"""
  id: str
  code: CodeableConcept
  display_name: str
  category: Literal["problem", "health-concern", "diagnosis", "encounter-diagnosis"] | None = 'diagnosis'
  clinical_status: ConditionStatus | None = None
  verification_status: VerificationStatus | None = None
  severity: Severity | None = None
  onset_date: date
  onset_age_description: str | None = None
  abatement_date: date | None = None
  recorded_date: date | None = None
  notes: str | None = None
  diagnosed_by: str | None = None
  caused_by: str | None = None
  complications: list[str] | None = None

class Allergy(BaseModel):
  """An allergy or intolerance (matches Oread patient.py:648)"""
  id: str
  code: CodeableConcept | None = None
  display_name: str
  category: AllergyCategory
  type: AllergyReactionType | None = None
  criticality: Literal["low", "high", "unable-to-assess"] | None = 'low'
  reactions: list[AllergyReaction] | None = None
  onset_date: date | None = None
  recorded_date: date | None = None
  clinical_status: Literal["active", "inactive", "resolved"] | None = 'active'
  verification_status: Literal["confirmed", "unconfirmed", "refuted", "entered-in-error"] | None = 'confirmed'
  notes: str | None = None

class PatientContext(BaseModel):
  """Shared patient context passed between platforms"""
  patient_id: str
  source: Literal["oread", "syrinx", "mneme"]
  name: str
  date_of_birth: date | None = None
  age_years: int | None = None
  age_months: int | None = None
  sex: Literal["male", "female", "other", "unknown"] | None = None
  problem_list: list[Condition] | None = None
  medication_list: list[Medication] | None = None
  allergy_list: list[Allergy] | None = None
  recent_encounters: list[EncounterSummary] | None = None
  family_history: str | None = None
  social_history: str | None = None

class EncounterContext(BaseModel):
  """Context for a specific encounter (from Syrinx)"""
  encounter_id: str
  patient: PatientContext
  chief_complaint: str
  encounter_type: Literal["acute", "well-child", "mental-health", "follow-up", "newborn"] | None = None
  script: list[ScriptLine] | None = None
  errors_injected: list[InjectedError] | None = None
  source: Literal["syrinx"] | None = None
  duration_tier: Literal["short", "medium", "long"] | None = None
